//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipio
    {
        public string MunicipioID { get; set; }
        public string MunicipioDescripcion { get; set; }
        public int ProvinciaID { get; set; }
    
        public virtual Provincia Provincia { get; set; }
    }
}
