//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordenes()
        {
            this.DetallesOrdenes = new HashSet<DetallesOrdenes>();
        }
    
        public int OrdenesID { get; set; }
        public string ClienteID { get; set; }
        public Nullable<System.DateTime> FechaOrdenes { get; set; }
        public Nullable<System.DateTime> FechaRequeida { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<int> ViaEnvio { get; set; }
        public Nullable<decimal> Flete { get; set; }
        public string NombreEnvio { get; set; }
        public string DireccionEnvio { get; set; }
        public string ProvinciaEnvio { get; set; }
        public string MunicipioEnvio { get; set; }
        public string CodigoPostalEnvio { get; set; }
        public string PaisEnvio { get; set; }
    
        public virtual Carrier Carrier { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesOrdenes> DetallesOrdenes { get; set; }
    }
}
