//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetallesOrdenes = new HashSet<DetallesOrdenes>();
        }
    
        public int ProductoID { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<int> SuplidorID { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public string CantidadPorUnidad { get; set; }
        public Nullable<decimal> PrecioUnidad { get; set; }
        public Nullable<short> UnidadesEnStock { get; set; }
        public Nullable<short> UnidadesPorTransaccion { get; set; }
        public Nullable<short> NivelPedidosDeStock { get; set; }
        public bool Discontinuado { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesOrdenes> DetallesOrdenes { get; set; }
        public virtual Suplidor Suplidor { get; set; }
    }
}
