//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suplidor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suplidor()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int SuplidorID { get; set; }
        public string NombreEmpresa { get; set; }
        public string NombreContacto { get; set; }
        public string ContactoCargo { get; set; }
        public string Direccion { get; set; }
        public string Provincia { get; set; }
        public string Municipio { get; set; }
        public string CodigoPostal { get; set; }
        public string pais { get; set; }
        public string Telefono { get; set; }
        public string PaginaWeb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
